# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OSMimport
                                 A QGIS plugin
 It imports easily the road map of the city and the stops for each public transport
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-12
        copyright            : (C) 2024 by Luigi Dal Bosco
        email                : luigi.dalbosco@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OSMimport class from file OSMimport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OSMimport_road_PTstops import OSMimport
    return OSMimport(iface)
